--EX 3
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME IN ('EMPLOYEES', 'DEPARTMENTS', 'JOBS', 'JOB_HISTORY', 'LOCATIONS', 'COUNTRIES', 'REGIONS')
ORDER BY TABLE_NAME, COLUMN_ID;

--EX 4
SELECT *
FROM EMPLOYEES;

--EX 5
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, HIRE_DATE
FROM EMPLOYEES;

--EX 6
--CU DUPLICATE
SELECT JOB_ID
FROM EMPLOYEES;

--FARA DUPLICATE
SELECT DISTINCT JOB_ID
FROM EMPLOYEES;

--EX 7
SELECT FIRST_NAME || ' ' || LAST_NAME || ', ' || JOB_ID AS "Angajat si titlu"
FROM EMPLOYEES;

--EX 8
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > 2850;

--EX 9
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 104;

--EX 10
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY NOT BETWEEN 1500 AND 2850;

--EX 11
SELECT FIRST_NAME, LAST_NAME, JOB_ID, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN TO_DATE('20-02-1987', 'DD-MM-YYYY')
          AND TO_DATE('01-05-1989', 'DD-MM-YYYY')
ORDER BY HIRE_DATE;

--EX 12
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (10, 30)
ORDER BY FIRST_NAME;

--EX 13
SELECT FIRST_NAME || ' ' || LAST_NAME AS "Angajat", SALARY AS "Salariu lunar"
FROM EMPLOYEES
WHERE SALARY > 1500 AND DEPARTMENT_ID IN (10, 30);

--EX 14
SELECT FIRST_NAME, LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;

--EX 15
--V1
SELECT FIRST_NAME, LAST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY COMMISSION_PCT DESC;
--V2
SELECT FIRST_NAME, LAST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
ORDER BY COMMISSION_PCT DESC;

--EX 16
SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE '__a%';

--EX 17
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE LOWER(FIRST_NAME) LIKE '%l%l%' AND DEPARTMENT_ID = 50 OR MANAGER_ID = 102;

--EX 18
SELECT FIRST_NAME, LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE (JOB_ID LIKE '%CLERK%' OR JOB_ID LIKE '%REP%') AND
      (SALARY NOT IN (1000, 2000, 3000));
