--EX 1
SELECT CONCAT(FIRST_NAME, ' ') || CONCAT(LAST_NAME, ' ') || 'castiga ' || SALARY || ' lunar dar doreste ' || SALARY * 3 AS "Salariul ideal"
FROM EMPLOYEES;

--EX 2
--V1
SELECT INITCAP(FIRST_NAME) AS FIRST_NAME, UPPER(LAST_NAME) AS LAST_NAME, LENGTH(LAST_NAME) AS NAME_LENGTH
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'J%' OR LAST_NAME LIKE 'M%' OR LAST_NAME LIKE '__a%'
ORDER BY LENGTH(LAST_NAME) DESC;
--V2
SELECT INITCAP(FIRST_NAME) AS FIRST_NAME,
       UPPER(LAST_NAME) AS LAST_NAME,
       LENGTH(LAST_NAME) AS NAME_LENGTH
FROM EMPLOYEES
WHERE SUBSTR(LAST_NAME, 1, 1) IN ('J', 'M')
   OR SUBSTR(LAST_NAME, 3, 1) = 'a'
ORDER BY LENGTH(LAST_NAME) DESC;

--EX 3
SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE TRIM(BOTH FROM LOWER(FIRST_NAME)) = 'steven';

--EX 4
SELECT EMPLOYEE_ID, LAST_NAME, LENGTH(LAST_NAME), INSTR(LOWER(LAST_NAME), 'a')
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%e';

--EX 5
SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE MOD(ROUND(SYSDATE) - HIRE_DATE, 7) = 0;

--EX 6
SELECT EMPLOYEE_ID, LAST_NAME, SALARY,
       ROUND(SALARY * 1.15, 2) AS "Salariu nou",
       ROUND((SALARY * 1.15) / 100, 2) AS "Numar sute"
FROM EMPLOYEES
WHERE MOD(SALARY, 1000) != 0;

--EX 7
SELECT LAST_NAME, SALARY, TRIM(LEADING ' ' FROM RPAD(' ', SALARY/1000 + 1, '$'))
FROM EMPLOYEES;

--EX 8
SELECT ADD_MONTHS(SYSDATE, 1)
FROM DUAL;

--EX 9
SELECT ROUND(TO_DATE('01-01-2026', 'DD-MM-YYYY') - SYSDATE, 2)
FROM DUAL;

--EX 10
--A)
SELECT SYSDATE + INTERVAL '12' HOUR
FROM DUAL;
--B)
SELECT SYSDATE + INTERVAL '5' MINUTE
FROM DUAL;

--EX 11
SELECT FIRST_NAME || ' ' || LAST_NAME AS "FULL NAME", HIRE_DATE, NEXT_DAY(HIRE_DATE + INTERVAL '6' MONTH, 'MONDAY') AS "NEGOCIERE"
FROM EMPLOYEES;

--EX 12
SELECT
    LAST_NAME AS "Nume",
    ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) AS "Luni lucrate"
FROM EMPLOYEES
ORDER BY "Luni lucrate";

--EX 13
SELECT
    LAST_NAME AS "Nume",
    HIRE_DATE AS "Data Angajării",
    TO_CHAR(HIRE_DATE, 'Day') AS "Zi",
    CASE
        WHEN TO_CHAR(HIRE_DATE, 'D') = '2' THEN 1 -- Luni
        WHEN TO_CHAR(HIRE_DATE, 'D') = '3' THEN 2 -- Marți
        WHEN TO_CHAR(HIRE_DATE, 'D') = '4' THEN 3 -- Miercuri
        WHEN TO_CHAR(HIRE_DATE, 'D') = '5' THEN 4 -- Joi
        WHEN TO_CHAR(HIRE_DATE, 'D') = '6' THEN 5 -- Vineri
        WHEN TO_CHAR(HIRE_DATE, 'D') = '7' THEN 6 -- Sâmbătă
        WHEN TO_CHAR(HIRE_DATE, 'D') = '1' THEN 7 -- Duminică
        END AS "Ordine"
FROM EMPLOYEES
ORDER BY "Ordine";

--EX 14
--V1
SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE, 'YYYY') = '1987';
--V2
SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE EXTRACT(YEAR FROM HIRE_DATE) = 1987;


--EX 15
SELECT
    LAST_NAME AS "Nume",
    NVL(TO_CHAR(COMMISSION_PCT * 100), 'Fara_comision') AS "Comision"
FROM EMPLOYEES;

--EX 16
SELECT LAST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE SALARY + NVL(SALARY * COMMISSION_PCT, 0) > 10000;

--EX 17
SELECT LAST_NAME,
       JOB_ID,
       SALARY,
       CASE
           WHEN JOB_ID = 'IT_PROG' THEN SALARY * 1.20
           WHEN JOB_ID = 'SA_REP'  THEN SALARY * 1.25
           WHEN JOB_ID = 'SA_MAN'  THEN SALARY * 1.35
           ELSE SALARY
           END AS "SALARIU DUPĂ MĂRIRE"
FROM EMPLOYEES;

