--EX 1
SELECT CONCAT(FIRST_NAME, ' ') || CONCAT(LAST_NAME, ' ') || 'castiga ' || SALARY || ' lunar dar doreste ' || SALARY * 3 AS "Salariul ideal"
FROM EMPLOYEES;

--EX 2
--V1
SELECT INITCAP(FIRST_NAME) AS FIRST_NAME, UPPER(LAST_NAME) AS LAST_NAME, LENGTH(LAST_NAME) AS NAME_LENGTH
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'J%' OR LAST_NAME LIKE 'M%' OR LAST_NAME LIKE '__a%'
ORDER BY LENGTH(LAST_NAME) DESC;
--V2
SELECT INITCAP(FIRST_NAME) AS FIRST_NAME,
       UPPER(LAST_NAME) AS LAST_NAME,
       LENGTH(LAST_NAME) AS NAME_LENGTH
FROM EMPLOYEES
WHERE SUBSTR(LAST_NAME, 1, 1) IN ('J', 'M')
   OR SUBSTR(LAST_NAME, 3, 1) = 'a'
ORDER BY LENGTH(LAST_NAME) DESC;

--EX 3
SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE TRIM(BOTH FROM LOWER(FIRST_NAME)) = 'steven';

--EX 4
SELECT EMPLOYEE_ID, LAST_NAME, LENGTH(LAST_NAME), INSTR(LOWER(LAST_NAME), 'a')
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%e';

--EX 5
SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE MOD(ROUND(SYSDATE) - HIRE_DATE, 7) = 0;

--EX 6


