--EX 1
SELECT DISTINCT JOB_TITLE
FROM JOBS
         JOIN EMPLOYEES ON JOBS.JOB_ID = EMPLOYEES.JOB_ID
WHERE DEPARTMENT_ID = 30;

--EX 2
SELECT LAST_NAME, JOB_TITLE, DEPARTMENT_NAME
FROM EMPLOYEES E
         JOIN JOBS J ON E.JOB_ID = J.JOB_ID
         JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE UPPER(LAST_NAME) LIKE '%A%';

--EX 3
SELECT LAST_NAME, JOB_TITLE, E.DEPARTMENT_ID, DEPARTMENT_NAME
FROM EMPLOYEES E
         JOIN JOBS J ON E.JOB_ID = J.JOB_ID
         JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
         JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
WHERE UPPER(L.CITY) LIKE '%OXFORD%';

--EX 4
SELECT J.JOB_ID, JOB_TITLE
FROM JOBS J
         JOIN EMPLOYEES E ON J.JOB_ID = E.JOB_ID
WHERE E.SALARY > 3000
   OR E.SALARY = (J.MIN_SALARY + J.MAX_SALARY) / 2;

--EX 5
SELECT E.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE
FROM EMPLOYEES E
         JOIN JOBS J ON E.JOB_ID = J.JOB_ID
         JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE UPPER(D.DEPARTMENT_NAME) LIKE '%TI%'
ORDER BY D.DEPARTMENT_NAME, E.LAST_NAME;

--EX 6
SELECT E.EMPLOYEE_ID AS "ANG#", E.LAST_NAME AS "ANGAJAT", M.MANAGER_ID AS "MGR#", M.LAST_NAME AS "MANAGER"
FROM EMPLOYEES E
         JOIN EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID
WHERE M.MANAGER_ID IS NOT NULL;

--EX 7
SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE > (SELECT HIRE_DATE FROM EMPLOYEES WHERE LAST_NAME = 'Gates');

--EX 8
SELECT E.EMPLOYEE_ID, E.LAST_NAME
FROM EMPLOYEES E
         JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.DEPARTMENT_ID IN (
    SELECT DISTINCT DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE LOWER(LAST_NAME) LIKE '%t%'
)
ORDER BY E.LAST_NAME;


