--EX 8
SELECT UNIQUE E.LAST_NAME, E.FIRST_NAME, D.DEPARTMENT_NAME, D.DEPARTMENT_ID
FROM EMPLOYEES E
         JOIN DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
         JOIN EMPLOYEES C ON E.DEPARTMENT_ID = C.DEPARTMENT_ID
WHERE UPPER(C.LAST_NAME) LIKE '%T%'
  AND C.LAST_NAME != E.LAST_NAME
ORDER BY E.LAST_NAME;

--EX 9
SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY, J.JOB_TITLE, C.COUNTRY_NAME, L.CITY
FROM EMPLOYEES E
         JOIN EMPLOYEES M ON E.MANAGER_ID = M.MANAGER_ID
         JOIN JOBS J ON E.JOB_ID = J.JOB_ID
         JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
         JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
         JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
WHERE M.LAST_NAME = 'King';

--Operatori pe mulţimi
--1
SELECT DEPARTMENT_ID
FROM DEPARTMENTS
WHERE UPPER(DEPARTMENT_NAME) LIKE '%RE%'
UNION
SELECT DEPARTMENTS.DEPARTMENT_ID
FROM DEPARTMENTS
         JOIN EMPLOYEES ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
WHERE EMPLOYEES.JOB_ID = 'SA_REP';

--2
SELECT DEPARTMENT_ID
FROM DEPARTMENTS
MINUS
SELECT DEPARTMENT_ID
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, D.DEPARTMENT_ID
FROM EMPLOYEES E
         RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE EMPLOYEE_ID IS NULL;

SELECT *
FROM EMPLOYEES E
WHERE E.SALARY > (SELECT MAX(E2.SALARY)
                  FROM EMPLOYEES E2
                  WHERE E2.DEPARTMENT_ID = 30);

SELECT T.FIRST_NAME,
       T.SAL_AN
FROM EMPLOYEES E2
         JOIN (SELECT E.FIRST_NAME,
                      E.SALARY * 12 AS SAL_AN
               FROM EMPLOYEES E
               WHERE E.DEPARTMENT_ID = 50) T ON E2.FIRST_NAME = T.FIRST_NAME;

--EX 1
SELECT E.FIRST_NAME,
       E.LAST_NAME,
       E.SALARY
FROM EMPLOYEES E;

SELECT E.LAST_NAME
FROM EMPLOYEES E
         JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE UPPER(D.DEPARTMENT_NAME) = (SELECT D.DEPARTMENT_NAME
                                  FROM DEPARTMENTS D
                                           JOIN EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
                                  WHERE UPPER(E.LAST_NAME) = 'Gates');

--GRESIT ^^^

--EX 2
SELECT
    E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY,(
        SELECT M.FIRST_NAME
        FROM EMPLOYEES M
        WHERE E.MANAGER_ID = M.EMPLOYEE_ID
    )
FROM EMPLOYEES E

--EX 3
