--EX1
SELECT FIRST_NAME || ' ' || LAST_NAME AS NAME, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (
    SELECT DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE LAST_NAME = 'Gates'
)
  AND LAST_NAME <> 'Gates';

--EX2
SELECT E.EMPLOYEE_ID, E.FIRST_NAME || ' ' || E.LAST_NAME AS NAME, E.SALARY, M.FIRST_NAME || ' ' || M.LAST_NAME AS MANAGER
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M ON M.EMPLOYEE_ID = E.MANAGER_ID;

--EX3
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS NAME
FROM EMPLOYEES E
WHERE E.SALARY > ALL (
    SELECT SALARY
    FROM EMPLOYEES
    WHERE UPPER(JOB_ID) LIKE '%CLERK%'
    )
ORDER BY E.SALARY DESC;

--EX4
SELECT
    E.FIRST_NAME || ' ' || E.LAST_NAME AS NAME,
    D.DEPARTMENT_NAME,
    E.SALARY
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID
WHERE E.COMMISSION_PCT IS NULL OR E.COMMISSION_PCT = 0
  AND M.COMMISSION_PCT IS NOT NULL OR M.COMMISSION_PCT <> 0;

--EX5
SELECT
    E.FIRST_NAME || ' ' || E.LAST_NAME AS NAME,
    D.DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.HIRE_DATE = (
    SELECT MIN(E2.HIRE_DATE)
    FROM EMPLOYEES E2
    WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID
)
ORDER BY DEPARTMENT_NAME;

--EX6 ?????????????
SELECT
    E.FIRST_NAME || ' ' || E.LAST_NAME AS NAME,
    E.DEPARTMENT_ID,
    E.SALARY
FROM EMPLOYEES E
WHERE (E.DEPARTMENT_ID, E.SALARY) IN (
    SELECT E2.DEPARTMENT_ID, E2.SALARY
    FROM EMPLOYEES E2
    WHERE E2.COMMISSION_PCT IS NOT NULL AND E2.COMMISSION_PCT <> 0
)
  AND E.EMPLOYEE_ID NOT IN (
    SELECT E3.EMPLOYEE_ID
    FROM EMPLOYEES E3
    WHERE E3.COMMISSION_PCT IS NOT NULL AND E3.COMMISSION_PCT <> 0
);

--EX7
SELECT
    E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLOYEE_NAME,
    E.SALARY,
    (
        SELECT E2.FIRST_NAME || ' ' || E2.LAST_NAME
        FROM EMPLOYEES E2
        WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID
          AND E2.SALARY = (
            SELECT MAX(SALARY)
            FROM EMPLOYEES E3
            WHERE E3.DEPARTMENT_ID = E2.DEPARTMENT_ID
        )
    ) AS TOP_COLLEAGUE
FROM EMPLOYEES E
WHERE E.MANAGER_ID = (
    SELECT EMPLOYEE_ID
    FROM EMPLOYEES
    WHERE MANAGER_ID IS NULL
);
