--1
SELECT P.ORAS,
       COUNT(DISTINCT R.ID_CLIENT)
FROM REZERVARI R
         JOIN PROPRIETATI P ON R.ID_PROPRIETATE = P.ID_PROPRIETATE
WHERE R.STATUS = 'CONFIRMATA'
GROUP BY P.ORAS;

--2
SELECT C.ID_CLIENT, C.NUME
FROM CLIENTI C
         JOIN (SELECT ID_CLIENT
               FROM REZERVARI
                        JOIN PLATI P ON REZERVARI.ID_REZERVARE = P.ID_REZERVARE
               GROUP BY ID_CLIENT
               HAVING COUNT(DISTINCT P.METODA) = 1
                  AND MIN(P.METODA) = 'CASH') RR ON C.ID_CLIENT = RR.ID_CLIENT
    AND C.ID_CLIENT IN (SELECT ID_CLIENT
                        FROM REVIEWS
                        WHERE RATING >= 2
                        GROUP BY ID_CLIENT
                        HAVING COUNT(*) >= 3);

--3
SELECT C.ID_CLIENT, C.NUME,
       SUM((DATA_CHECK_OUT - DATA_CHECK_IN) * PR.PRET_PER_NOAPTE) AS TOTAL_CHELTUIELI
FROM CLIENTI C
         JOIN REZERVARI R ON C.ID_CLIENT = R.ID_CLIENT
         JOIN PROPRIETATI PR ON R.ID_PROPRIETATE = PR.ID_PROPRIETATE
GROUP BY C.ID_CLIENT, C.NUME
ORDER BY TOTAL_CHELTUIELI DESC
FETCH FIRST (
SELECT COUNT(DISTINCT ID_PROPRIETATE) AS N
FROM REZERVARI
WHERE TO_CHAR(DATA_CHECK_IN, 'YYYY') = '2025'
         ) ROWS ONLY;

