--1
SELECT A.NUME, COUNT(DISTINCT C.ID_ARTIST_DESCHIDERE)
FROM ARTISTI A
         JOIN TURNEE T ON A.ID_ARTIST = T.ID_ARTIST
         JOIN CONCERTE C ON T.ID_TURNEU = C.ID_TURNEU
         JOIN ARTISTI A2 ON C.ID_ARTIST_DESCHIDERE = A2.ID_ARTIST
WHERE A2.TIP = 'FORMATIE'
GROUP BY A.NUME;

--2
SELECT AR.NUME, COUNT(AL.ID_ALBUM)
FROM ARTISTI AR
         JOIN (SELECT ID_ARTIST, MAX(AN_DECERNARE) AS ULTIM_PREMIU
               FROM PREMII_CASTIGATE
               GROUP BY ID_ARTIST) PC ON AR.ID_ARTIST = PC.ID_ARTIST
         JOIN ALBUME AL ON AR.ID_ARTIST = AL.ID_ARTIST
    AND AL.AN_LANSARE < PC.ULTIM_PREMIU
WHERE AR.ID_ARTIST IN (SELECT T.ID_ARTIST
                       FROM TURNEE T
                                JOIN CONCERTE C ON T.ID_TURNEU = C.ID_TURNEU
                       WHERE TO_CHAR(C.DATA, 'YYYY') = '2024'
                       GROUP BY T.ID_ARTIST
                       HAVING COUNT(*) >= 3)
GROUP BY AR.NUME;

--3
SELECT A.NUME,
       SUM(C.VENIT)
FROM CONCERTE C
         JOIN TURNEE T ON C.ID_TURNEU = T.ID_TURNEU
         JOIN ARTISTI A ON T.ID_ARTIST = A.ID_ARTIST
WHERE TO_CHAR(C.DATA, 'YYYY') = '2025'
  AND C.ID_ARTIST_DESCHIDERE IN (SELECT PC.ID_ARTIST
                                 FROM PREMII_CASTIGATE PC
                                 GROUP BY PC.ID_ARTIST
                                 HAVING COUNT(*) >= 3)
GROUP BY A.NUME;

